# Generated by Django 3.1.1 on 2020-09-21 23:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('ifsc_code', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[api.models.validateIfsc])),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=180)),
            ],
        ),
    ]
